beatstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('niggersadmin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('core.urls', namespace='core')),
    path('password_reset_confirm/<uidb64>[0-9A-Za-z_\-]/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name="core.password_reset_confirm.html"), name="password_reset_confirm"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="core/password_reset_sent.html"), name="password_reset_done"),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="core/password_reset_complete.html"), name="password_reset_complete")
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve 
from django.conf.urls import url
from core import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from .views import (
    CheckoutView,
    PaymentView)



app_name = 'core'

urlpatterns = [
	path('home/', views.home, name='home'),
    path('', views.home_again, name='home-again'),
    path('logout/', views.logout_request, name='logout'),
    path('get-contacts/', views.contact_list, name='contact-list'),
    path('beat-store/', views.beat_store, name='beat-store'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('withdraw-contact/', views.withdraw_contact, name='withdraw-contact'),
    path('contact-us/', views.contact_view, name='contact'),
    path('bangare/', views.bangare, name="club"),
    path('randb/', views.randb, name="urban"),
    path('afroblues/', views.afroblues, name="dirtysouth"),
    path('afropop/', views.afropop, name="gangsta"),
    path('reggaeton/', views.reggaeton, name="reggaeton"),
    path('pop/', views.pop, name="pop"),
    path('rate/<int:pk>/', views.rate_beat, name='rate-beat'),
    path('purchased/', views.purchased, name="purchased"),
	path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit-profile'),
    path('profile-contact/', views.contactprof_view, name='contact-prof-view'),
    path('contactprof-del/', views.contactprof_delete, name='contactprof_del'),
    path('search/', views.results, name='results'),
    path('searchq/', views.results_prof, name='results-prof'),
    path('order-summary/', views.order_summary, name='order-summary'),
    path('add-to-cart/<str:slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('my-orders/', views.my_orders, name="my-orders"),
    path('contact-orders/', views.contact_orders, name='conatct-orders'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('admin-list/', views.admin_beat_list, name='admin-beat-list'),
    path('admin-list/<str:slug>', views.admin_beat_detail, name='admin-beat-detail'),
    path('del/<str:slug>', views.admin_delete, name="admin-delete"),
    path('verify/<str:slug>', views.admin_verify, name="admin-verify"),
    path('unverify/<str:slug>', views.admin_unverify, name="admin-unverify"),
    path('<str:slug>/license/', views.license_view, name='license-view'),
    path('payment-options/', views.payment_options, name="payment-options"),
    path('upload-beat/', views.beat_form_view, name='beat-form-view'),
    path('my-beats', views.beat_list_view, name='beat-list-view'),
    path('my-beats/<str:slug>/', views.beat_detail_view, name='beat-detail-view'),
    path('<str:slug>/edit', views.beat_update_view, name='beat-update'),
    path('<str:slug>/delete', views.beat_delete_view, name='beat-delete'),
    path('process/', views.payment_process, name="process"),
    path('done/', views.payment_done, name="done"),
    path('canceled', views.payment_canceled, name='canceled'),
    path('payment/stripe/', PaymentView.as_view(), name='payment-stripe'),
    path('payment/paystack/', views.paystack_payment, name="payment-paystack"),
    path('paystack/connect/<int:pk>/', views.paystack_payment_prof, name="payment-paystack-prof"),
    path('payment/paystack/ref', views.otp_page, name="otp-page"),
    path('paystack/connect/ref', views.otp_page_prof, name="otp-page-prof"),
    path('payment/paystack/phone', views.phone_page, name="phone-page"),
    path('paystack/connect/phone', views.phone_page_prof, name="phone-page-prof"),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="core/password_reset.html"), name="reset_password"),
    #path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="core/password_reset_sent.html"), name="password_reset_done"),
    #path('password_reset_confirm/', auth_views.PasswordResetConfirmView.as_view(template_name="core.password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="core/password_reset_complete.html"), name="password_reset_complete")

]


# password_reset_confirm/<uidb64>[0-9A-Za-z_\-]/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG == True:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ]

core/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from django_bitcoin.models import balance_changed, balance_changed_confirmed
from django.dispatch import receiver


# Create your models here.

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

GENRE_CHOICES = (
    ('Cl', 'Club'),

    ('P', 'Pop'),
    ('RG', 'Reggaeton'),
    ('U', 'Underground'),
    ('A', 'Afro'),
    ('AP', 'Afro Pop'),
    ('AR', 'Afro Reggae'),
    ('R&B', 'Afro R&B'),
    ('AB', 'Afro Blues'),
    ('B', 'Bangare')
)

MOOD_CHOICES = (
    ('A', 'Angry'),
    ('D', 'Dark'),
    ('E', 'Epic'),
    ('F', 'Frantic'),
    ('H', 'Happy'),
    ('I', 'Inspiring'),
    ('R', 'Relaxed'),
    ('S', 'Sad'),
    ('Si', 'Silly'),
    ('So', 'Soulful'),
)


SKILL_CHOICES = (
    ('m', 'Musician'),
    ('p', 'Producer'),
    ('ma', 'Manager'),
    ('pro', 'PRO'),
    ('co', 'Compose'),
    ('sw', 'Songwriter'),
    ('lb', 'Label brand & Sponsor'),
    ('di', 'Director'),
    ('mo', 'Model'),
    ('pa', 'Painter'),
    ('st', 'Stylist'),
    ('ac', 'Actor'),
    ('me', 'Media'),
    ('de', 'Designer'),
    ('pg', 'Photographer'),
    ('pt', 'Poet'),
    ('bd', 'Band'),
    ('tc', 'Teacher'),
    ('dc', 'Dancer'),
    ('cm', 'Comedian'),
    ('so', 'Show Organizers'),
)


class Profile(models.Model):
    profile_pic = models.FileField(upload_to='profile-pic')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    skill = models.CharField(choices=SKILL_CHOICES, max_length=4)
    

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class ContactProf(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    price = models.IntegerField()
    company_name = models.CharField(max_length=100, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.user.username
 

class OrderContactProf(models.Model):
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)
    ordered = models.BooleanField(default=False)
    contact = models.ForeignKey(ContactProf, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.user.username




class Beat(models.Model):
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(unique=True, blank=False)
    producer_name = models.CharField(max_length=45)
    beat_name = models.CharField(max_length=40)
    sound = models.FileField()
    sound_two = models.FileField()
    license = models.TextField()
    genre1 = models.CharField(choices=GENRE_CHOICES, max_length=3)
    mood1 = models.CharField(choices=MOOD_CHOICES, max_length=2)
    price = models.FloatField()
    verified = models.BooleanField(default=False)
    thumbnail = models.ImageField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	return f"{self.user.username}'s {self.beat_name}, verified-{ self.verified}"

class Rating(models.Model):
    beat = models.ForeignKey(Beat, on_delete=models.CASCADE)
    rate = models.IntegerField(default=0)

    def __str__(self):
        return self.beat.beat_name

class MassRate(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    beat = models.ForeignKey(Beat, on_delete=models.CASCADE)
    rate = models.IntegerField(default=0)

class SellersPay(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    withdraw = models.FloatField()

    def __str__(self):
        return self.user.username




class OrderBeat(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    beat = models.ForeignKey(Beat, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    #beat_owner = models.Foreign(User, default=1, null=True, on_delete=models.SET_NULL)


    def __str__(self):
        return f"{self.user.username} order {self.beat.beat_name}"



    def get_total_item_price(self):
        return self.beat.price

    def get_final_price(self):
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    beat = models.ManyToManyField(OrderBeat)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def get_total(self):
        total = 0
        for order_item in self.beat.all():
            total += order_item.get_total_item_price()
        return total



    def __str__(self):
        return self.user.username

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'



def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

class Contact(models.Model):
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email

class Cash(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cash = models.IntegerField()
@receiver(balance_changed)
def balance_changed_handler(sender, **kwargs):
    pass
    # try:
    # print "balance changed", sender.id, kwargs["changed"], sender.total_balance()


@receiver(balance_changed_confirmed)
def balance_changed_confirmed_handler(sender, **kwargs):
    pass


class ContactCash(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cash = models.IntegerField()

    def __str__(self):
        return self.user.username


class Withdraw(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField()
    bank_name = models.CharField(max_length=20)
    amount = models.IntegerField()
    account_number = models.CharField(max_length=15)

    def __str__(self):
        return self.name

core/templates/core/admin_list.html
{% extends 'core/base.html' %}
{% block content %}

{% if request.user.is_authenticated and request.user.is_staff %}
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<div class="container">
			
                   <h1 class="footer_title">All Beats</h1>
	{% for obj in beats %}

		<div>
			<p><a href="/admin-list/{{ obj.slug }}">{{ obj.beat_name }}</a> was uploaded by {{ obj.user }} at {{ obj.timestamp }} - Verification status: {{ obj.verified }}</p><hr>
		</div>
	{% endfor %}
	</div>
{% endif %}



{% endblock %}

core/templates/core/contact_orders.html
{% extends 'core/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<div class="ms_profile_wrapper">

    <div class="container">
        {%if message %}

            <div style="padding-top: 40px" class="container"><h1 style="font-size: 20px"><b> {{ message }}</b></a></p>
            </div>

        {% endif %}
        {% if contact %}
            <div style="padding-top: 40px" class="container"><h1 style="font-size: 20px">Total Amount: <b>&#8358 {{ total }}</b></h1> <p><a href="/withdraw-contact/">Withdraw</a></p>
            </div>

            {% for obj in contact %}
                
        <div class="card-body">

                    <p style="padding-top: 30px"><b>+ &#8358 {{ obj.contact.price}} </b> -{{ obj.user }} ordered your contact at <small>{{ obj.timestamp }}</small></p>
        </div>

            {% endfor %}
        {% else %}
            <div style="padding-top: 40px" class="container"><h1 style="font-size: 20px">NO order at the present moment , check back later</b></h1> </div>
        {% endif %}
    </div>
</main>
{% endblock %}

core/templates/core/edit_profile.html
{% extends 'core/base.html' %}
{% block content %}

<form method="POST" enctype='multipart/form-data'>{% csrf_token %}
</br>
		<div class="ms_profile_wrapper">
                <h1> Update Profile </h1>
                <div class="ms_profile_box">

                    <div class="ms_pro_form">
                        <div class="form-group">
                            <label>Profile Picture *</label>
                            <input type="file" name="profile_pic" value="{{ instance.profile_pic.url }}" id="profile_pic" class="form-control" required="True">
                        </div>

                    	<div class="form-group">
                            {% if name_exists%}
                                <b style="color: red">{{ name_exists }}</b><br>
                            {% endif %}
                            <label>Username</label>
                            <input type="text" name="username" value="{{ instance.user.username }}" placeholder="Username" class="form-control" required="True">
                        </div>

                        <div class="form-group">
                            <label>Full name *</label>
                            <input type="text" name="full_name" value="{{ instance.full_name }}" placeholder="Bella Scott" class="form-control" required="True">
                        </div>
                        <div class="form-group">
                            {% if email_error %}
                                <b style="color: red"> {{ email_error }}</b><br>
                            {% endif %}
                            <label>Your Email *</label>
                            <input type="email" name="email" value="{{ instance.email }}" placeholder="bella.scott@dummymail.com" class="form-control" required="True">
                        </div>
                         <div class="form-group">
                            <label>Address</label>
                            <input type="text" name="address" value="{{ instance.address }}" placeholder="3, Olokun Street, London" class="form-control" required="True">
                        </div>

                         <div class="form-group">
                            <label>City</label>
                            <input type="text" name="city" placeholder="London" value="{{ instance.city }}" class="form-control" required="True">
                        </div>

                         <div class="form-group">
                            <label>State</label>
                            <input type="text" name="state" placeholder="Quebec"  value="{{ instance.state }}" class="form-control" required="True">
                        </div>

                         <div class="form-group">
                            <label>Country</label>
                            <input type="text" name="country" placeholder="United Kingdom" value="{{ instance.country }}" class="form-control" required="True">
                        </div>

                         <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" name="phone" placeholder="Phone Number"   value="{{ instance.phone }}" class="form-control" required="True">
                        </div><br>
                        <div class="form-group">
                            <label for="skill">Skill:</label>
                              <select name="skill" id="skill">
                                <option value="{{ instance.get_skill_display }}">{{ instance.get_skill_display }}</option>
                                <option value="m">Musician</option>
                                <option value="p">Producer</option>
                                <option value="ma">Manager</option>
                                <option value="pro">PRO</option>
                                <option value="co">Compose</option>
                                <option value="sw">Songwriter</option>
                                <option value="lb">Label brand & Sponsor</option>
                                <option value="di">Director</option>
                                <option value="mo">Model</option>
                                <option value="pa">Painter</option>
                                <option value="st">Stylist</option>
                                <option value="ac">Actor</option>
                                <option value="me">Media</option>
                                <option value="de">Designer</option>
                                <option value="pg">Photographer</option>
                                <option value="pt">Poet</option>
                                <option value="bd">Band</option>
                                <option value="tc">Teacher</option>
                                <option value="dc">Dancer</option>
                                <option value="cm">Comedian</option>
                                <option value="so">Show Organizers</option>
                              </select>
                        </div>

                 
                        <div class="pro-form-btn text-center marger_top15">

                        	
                            <button class="ms_btn" type="submit">  Update </button> 
                            
          					
          				</div>
                    </div>
                </div>
            </div>
   </form>

{% endblock %}

core/templates/core/gangsta.html
{% extends 'core/base.html' %}
{% block content %}
<br>
<br>
<br>
<div class="ms_weekly_wrapper" >
                <div class="ms_weekly_inner">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="ms_heading">
                                <h1 style="margin-left: 105px;">AfroPop Beats</h1>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 padding_right40" style="padding-left: 55px;">
 
                           {%for obj in beat %}
                
                            <div class="ms_weekly_box">
                                <div class="weekly_left">
                                    <span class="w_top_no">
                                        {{ forloop.counter }}
                                    </span>
                                    <div class="w_top_song">
                                        <div class="w_tp_song_img">
                                            <img  style="width: 400%" src="{{ obj.thumbnail.url }}" alt="" class="img-fluid">
                                            <div class="ms_song_overlay">
                                            </div>
                                            <div class="ms_play_icon">
                                                <img src="images/svg/play.svg" alt="">
                                            </div>

                                        </div>
                                        <div class="w_tp_song_name">
                                            <h3><a href="{{ obj.sound_two.url}}" target="_blank">{{ obj.beat_name }}</a></h3>
                                            <p>Genre : {{ obj.get_genre1_display }}</p>
                                            <p>Mood : {{ obj.get_mood1_display }}, {{ obj.get_mood2_display }}</p>
                                            <p>Price : &#8358 {{ obj.price }}</p>
                                            <p><a href="/{{ obj.slug }}/license">Add to cart</a></p>
                                            <audio controls>
                                                <source src="{{ obj.sound_two.url }}" type="audio/mpeg">
                                            </audio>
                                        </div>
                                    </div>
                                </div>
                                <div class="weekly_right">
                                    <span class="w_song_time">0:15</span>
                                    <span class="ms_more_icon" data-other="1">
                                        <img src="images/svg/more1.svg" alt="">                                 
                                    </span>
                                </div>
                                <ul class="more_option">
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_fav"></span></span>Add To Favourites</a></li>
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_queue"></span></span>Add To Queue</a></li>
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_dwn"></span></span>Download Now</a></li>
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_playlst"></span></span>Add To Playlist</a></li>
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_share"></span></span>Share</a></li>
                                </ul>
                            </div>
                            <div class="ms_divider"></div>
                        {% endfor %}

                            <!--  -->
                        </div>
                        <!-- -->
                        </div>
                    </div>
                </div>
            </div>
						

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

  {% block content %}

<form method="POST">{% csrf_token %}
</br>
		<div class="ms_profile_wrapper">
                <h1>Sign Up</h1>
                <div class="ms_profile_box">
					<div class="ms_pro_form">
						<div class="form-group">
                            <label>Username</label>
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>

                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" placeholder="******" class="form-control" name="password">
                        </div>

                        <div class="pro-form-btn text-center marger_top15">
							
                            <button class="ms_btn" type="submit">Login</button> 
						</div>
						
						<p>Don't Have An Account? <a href="#myModal1" data-toggle="modal" class="ms_modal hideCurrentModel">Signup here</a></p>

                    </div>
                </div>
            </div>
   </form>
     {% endblock %}

core/templates/core/otp_page.html
{% extends 'core/base.html' %}
{% block content %}

<br>
<br>
<br>
<br>
<br>

<div class="ms_profile_wrapper">
                <h1>Pay with your card</h1>
                
                <div class="ms_profile_box">
          
                   <form method="POST">{% csrf_token %}
                    <div class="ms_pro_form">
                        <div class="form-group">
                            <label>OTP*</label>
                            <input type="text" placeholder="123456" name="otp" id="otp" class="form-control" required="True">
                        </div>
                        <div class="form-group">
                            <label>Reference *</label>
                            <input type="text" placeholder="xRS45y6FGCfoP5y"  name="ref" id="ref" class="form-control" required="True">
                        </div>
                    
                        <div class="pro-form-btn text-center marger_top15">
                            <button style="border-radius: 12px; width: 120px; background: white;"value="submit">Submit</button>
                        </div>
                    </div>
                	</form>
                </div>
            </div>
{% endblock %}

core/templates/core/password_reset.html
{% extends 'core/base.html' %}
{% block content %}

{% load static %}

<br>
<br>
<br>
<title>Afro Beat | Reset Password</title>

 <center>
      <p>Reset Password</p>
     <br>
     <p>Forgotten your password? Enter your email and we will send the instructions for creating a new one</p>
   	<form method="post">{% csrf_token %}
    	{{ form.as_p}}

  		<button type="submit">Reset Password</button>    
  	</form> 
</center>
                      
  

{% endblock %}

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% block content %}


<br>  
<br>
<br>   
<br> 
<br> 
            <div class="ms_profile_wrapper">
                <h1> Welcome back {{ user }}</h1>
                <div class="ms_profile_box">
                    <div class="ms_pro_form">
                        <div class="form-group">
                            <img  style="border-radius: 12px;" src="{{ user.profile.profile_pic.url }}" alt="" class="img-fluid">
                        </div><br>
                        <div class="form-group">
                            <label>Full Name : {{ user.profile.full_name }}</label>
                        </div>
                        <div class="form-group">
                            <label>Aka : {{ user.username }}</label>
                        </div>

                        <div class="form-group">
                            <label>Address : {{ user.profile.address }}</label>
                        </div>

                        <div class="form-group">
                            <label>Email : {{ user.profile.email }}</label>
                        </div>

                        <div class="form-group">
                            <label>City : {{ user.profile.city }}</label>
                        </div>

                        <div class="form-group">
                            <label>State : {{ user.profile.state }}</label>
                        </div>

                        <div class="form-group">
                            <label>Country : {{ user.profile.country }}</label>
                        </div>

                       <div class="form-group">
                            <label>Phone : {{ user.profile.phone }}</label>
                        </div>

                        <div style="padding-left: 5%; padding-top: 20px" class="form-group">
                            <label>Skill : {{ user.profile.get_skill_display }}</label>
                        </div> </center>
                        <br>
                        <br>
                        
                        {%if cash%}
                        <a href="/contactprof-del/">Delete contact</a><br>
                        {% else %}
                        <p>Want to keep your contact secret and sell it to people taht are interested. Click <a href="/profile-contact/">here</a></p>
                        <br>
                        {% endif %}
                        <!-- <a href="edit/">Edit Profile</a> -->

                    </div>

                </div>

            </div>





{% endblock %}